services:
  app:
    build: ./web_server
    ports:
      - 8081:8081
    networks:
      - bridge1
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - bridge1
    restart: unless-stopped
    volumes:
      - ./data:/data
networks:
  bridge1:
    driver: bridge
